export const weatherImages = {
  "Partly Cloudy": require("../assets/images/partlycloudy.png"),
  "Moderate rain": require("../assets/images/moderaterain.png"),
  "Patchy rain possible": require("../assets/images/moderaterain.png"),
  Sunny: require("../assets/images/sun.png"),
  Clear: require("../assets/images/sun.png"),
  Overcast: require("../assets/images/cloud.png"),
  Cloudy: require("../assets/images/cloud.png"),
  "Light rain": require("../assets/images/moderaterain.png"),
  "Moderate rain at times": require("../assets/images/moderaterain.png"),
  "Heavy rain": require("../assets/images/heavyrain.png"),
  "Heavy rain at times": require("../assets/images/heavyrain.png"),
  "Moderate or heavy freezing rain": require("../assets/images/heavyrain.png"),
  "Moderate or heavy rain shower": require("../assets/images/heavyrain.png"),
  "Moderate or heavy rain with thunder": require("../assets/images/heavyrain.png"),
  other: require("../assets/images/moderaterain.png"),
};

export const weatherBackgroundImages = {
  "Partly Cloudy": require("../assets/images/cloudBackground.jpg"),
  "Moderate rain": require("../assets/images/cloudBackground.jpg"),
  "Patchy rain possible": require("../assets/images/cloudBackground.jpg"),
  Sunny: require("../assets/images/sunnyBackground.jpg"),
  Clear: require("../assets/images/sunnyBackground.jpg"),
  Overcast: require("../assets/images/sunnyBackground.jpg"),
  Cloudy: require("../assets/images/cloudBackground.jpg"),
  "Light rain": require("../assets/images/rainBackground.jpg"),
  "Moderate rain at times": require("../assets/images/rainBackground.jpg"),
  "Heavy rain": require("../assets/images/rainBackground.jpg"),
  "Heavy rain at times": require("../assets/images/rainBackground.jpg"),
  "Moderate or heavy freezing rain": require("../assets/images/rainBackground.jpg"),
  "Moderate or heavy rain shower": require("../assets/images/rainBackground.jpg"),
  "Moderate or heavy rain with thunder": require("../assets/images/rainBackground.jpg"),
  other: require("../assets/images/sunnyBackground.jpg"),
};
